### ISSUE TITLE
Failed to connect to Geth from python, Connection Refused. 

### ISSUE THREAD

**Issue by colm** [pipermerriam/ethereum-rpc-client#14]
Python: 
`
from eth_rpc_client import Client
import networkx as nx
import matplotlib.pyplot as plt

import pdb

client = Client(host="127.0.0.1", port="8545")
transactions={}

for i in range(1213400,1213401):
  blk = client.get_block_by_number(i)
  for trans in blk[u'transactions']:
    if trans[u'from'] not in transactions.keys():
      transactions[trans[u'from']] = {trans[u'to']:int(trans[u'value'],16)}
    elif trans[u'to'] not in transactions[trans[u'from']].keys():
      transactions[trans[u'from']][trans[u'to']] = int(trans[u'value'],16)
    else:
      transactions[trans[u'from']][trans[u'to']] += int(trans[u'value'],16)

`
geth
`geth --rpcaddr "localhost" --rpcport "8545" console 2>> out.txt`

PythonERROR: 
`Traceback (most recent call last):
  File "get.py", line 11, in <module>
    blk = client.get_block_by_number(i)
  File "/usr/local/lib/python2.7/dist-packages/ethereum_client_utils-0.3.1-py2.7.egg/eth_client_utils/client.py", line 199, in get_block_by_number
    "eth_getBlockByNumber", [block_number_as_hex, full_transactions],
  File "/usr/local/lib/python2.7/dist-packages/ethereum_rpc_client-0.4.4-py2.7.egg/eth_rpc_client/client.py", line 20, in make_request
    data=request_data,
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fdeeaba8550>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

Geth ERROR:
`E0506 21:25:10.486092 core/tx_pool.go:454] could not get current state: Missing trie node cc1b1dcf26e6cda8fb478623240eb7a04035b2d252f640ee5e696491113c1df7
E0506 21:25:10.497401 core/tx_pool.go:454] could not get current state: Missing trie node cc1b1dcf26e6cda8fb478623240eb7a04035b2d252f640ee5e696491113c1df7
E0506 21:25:10.504642 core/tx_pool.go:454] could not get current state: Missing trie node cc1b1dcf26e6cda8fb478623240eb7a04035b2d252f640ee5e696491113c1df7
`

**Comment by colm** [comment]
had to use -rpc option in geth not just 
'geth --rpcaddr "localhost" --rpcport "8545" console 2>> out.txt'

thanks
